#fix for 0.14.3 - https://github.com/greshake/i3status-rust/issues/965
native_separators = true

idle_bg = "#1d2635CC"
idle_fg = "#e1ebee"
info_bg = "#9da4a6DD"
info_fg = "#1d2635"
good_bg = "#D3DAD8DD"
good_fg = "#1d2635"
warning_bg = "#e1ebeeDD"
warning_fg = "#1d2635"
critical_bg = "#dc322fDD" 
critical_fg = "#1d2635"
separator = "|"
separator_bg = "#1d2635CC"
separator_fg = "#D3DAD8"
alternating_tint_bg = "#00000000"
alternating_tint_fg = "#00000000"
