[theme]
file = "/home/jorderator/.config/status-theme.toml"

[icons]
name = "awesome5"
[icons.overrides]
pomodoro = "  "


# move to using this, and in python script
[[block]]
block = "custom_dbus"
name = "NotifBlock"
initial_text = " - "
on_click = "rm /tmp/alerting_active"

#[[block]]
#block = "custom"
#command = "cat /tmp/notif.txt | grep text"
#json = true
#interval = 1
#on_click = "rm /tmp/alerting_active"

[[block]]
block = "disk_space"
path = "/"
info_type = "available"
unit = "GB"
format = "{path} {available}"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "net"
device = "wlan0"
interval = 1
#format = "{graph_up} {speed_up} - {graph_down} {speed_down} on {ssid} ({signal_strength}) - {ip}"
format = "{ssid} {signal_strength} {ip} {speed_up;K} {speed_down;K}"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

#[[block]]
#block = "cpu"
#interval = 1

[[block]]
block = "sound"
step_width = 2
show_volume_when_muted = true

[[block]]
block = "battery"
driver = "upower"
device = "DisplayDevice"
interval = 5
format = "{percentage} {time}"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "time"
interval = 1
format = "%a %b (%m) %d %Y %H/%l:%M:%S"
