#!/bin/bash

path="/sys/class/backlight/intel_backlight"
value=$(cat $path/brightness)
max=$(cat $path/max_brightness)
increment=$(calc -dp "round($max / 100 * $1, 0)")

if [[ $(($value + $increment)) -gt 0 && $(($value + $increment)) -lt $max ]]; then
	value=$(($value + $increment))
fi
echo -n $value > $path/brightness
