#!/bin/bash

value=$(cat /sys/class/backlight/intel_backlight/brightness)
if [[ $(($value + $1)) -gt 0 && $(($value + $1)) -lt 188 ]]; then
	value=$(($value + $1))
fi
echo -n $value > /sys/class/backlight/intel_backlight/brightness
