#!/bin/bash

cp /etc/pacman.d/mirrorlist /etc/pacman.d/backups/mirrorlist-backup-$(date +'%m%d%H%M%S')

pacman -Sy
#reflector -c australia --sort rate > /etc/pacman.d/mirrorlist
#reflector --score 15 --sort rate >> /etc/pacman.d/mirrorlist
reflector -c australia --sort rate --protocol https --download-timeout 30 --connection-timeout 30 --save /etc/pacman.d/mirrorlist
