#!/bin/bash

function brightness {
	if [[ $1 = "" || $2 = "" ]]; then
		exit 1
	fi

	path="/tmp/.brightness_$1"
	if [[ ! -f $path ]]; then
		echo "1" > $path
	fi

	value=$(cat $path)
	newvalue=$(echo "$value + (0 $2)" | bc)

	if (( $(echo "$newvalue <= 1" | bc) && $(echo "$newvalue >= 0" | bc) )); then
		value=$newvalue
	fi

	xrandr --output $1 --brightness $value

	echo $value > $path
}


if [[ $1 = "all" ]]; then
	if [[ $2 = "same" ]]; then
		xrandr --output HDMI-1 --same-as eDP-1
		xrandr --output DP-1 --same-as eDP-1

	elif [[ $2 = "brightness" ]]; then
		brightness HDMI-1 $3
		brightness DP-1 $3
		brightness eDP-1 $3

	elif [[ $2 = "off" ]]; then
		xrandr --output HDMI-1 --off
		xrandr --output DP-1 --off
	fi

elif [[ $2 = "same-as" ]]; then
	echo "[$1 same as $3]"
	xrandr --output $1 --auto --same-as $3

elif [[ $2 = "left-of" ]]; then
	echo "[$1 left of $3]"
	xrandr --output $1 --auto --left-of $3

elif [[ $2 = "below" ]]; then
	echo "[$1 below $3]"
	xrandr --output $1 --auto --below $3

elif [[ $2 = "above" ]]; then
	echo "[$1 above $3]"
	xrandr --output $1 --auto --above $3

elif [[ $2 = "right-of" ]]; then
	echo "[$1 right of $3]"
	xrandr --output $1 --auto --right-of $3

elif [[ $2 = "brightness" ]]; then
	if [[ $3 = "" ]]; then
		echo "please provide a value to modify brightness with"
	else
		brightness $1 $3
	fi

elif [[ $2 = "off" ]]; then
	xrandr --output $1 --off
fi

$HOME/.fehbg
